### ISSUE TITLE
Illegal redirect_uri

### ISSUE THREAD

**Issue by ArmatorPL** [radujica/tospotify#18] opened 2022-04-20 17:52 UTC
Hi, I have seen a closed ticket on that topic but would like to raise the same issue.
I am getting the same error: Illegal redirect_uri
This message appears in my browser after I run the command (python -m tospotify "my_spotify_email" "playlist_path.m3u").
![image](https://user-images.githubusercontent.com/36926807/164292339-b2f5d276-4605-4b0f-aaff-bc2b741265b5.png)

I have tried different URIs (http://localhost:8080/; http://localhost:8080; http://localhost:8888/; ...). 
Of course setting it up in both the spotify dev dashboard and with "set SPOTIPY_REDIRECT_URI" but still getting that error.

**Comment by ArmatorPL** [comment] 2022-04-28 14:17
No love for me? :)

**Comment by radujica** [comment] 2022-04-28 15:11
Hard to debug this :|

First double-check this part from the issue you hinted about: https://github.com/radujica/tospotify/issues/6#issuecomment-706762663

If still an issue, please list your:
- OS
- Python version
- tospotify version (from `pip list`) <- if it's not the latest, a first thing to do would be to try that one (0.3.1)

and double-check that the `SPOTIPY_REDIRECT_URI` envvar exists in the terminal you are trying to use tospotify in; for Windows `cmd`, typing `set` would show all environment variables.

And we can take it from there :)

**Comment by ArmatorPL** [comment] 2022-05-02 07:08
Thanks! Will check it and get back to you.

**Comment by ArmatorPL** [comment] 2022-05-11 09:26
Thanks again for the answer. I went through all steps again but the issue still persists. `set`  in `cmd` gives me the right redirect URI  (same URI as in Spotify Dashboard). 

OS: W10
Python: Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37)
tospotify: 0.3.1

**Comment by radujica** [comment] 2022-05-17 16:10
I can confirm it works for me in that setup. This is how it looks like:

![image](https://user-images.githubusercontent.com/8166962/168857150-9557fcf1-3365-4748-bca5-3e61417de1c5.png)
![image](https://user-images.githubusercontent.com/8166962/168857678-c75717d5-c3e4-4362-b269-497ad75c0fa0.png)
![image](https://user-images.githubusercontent.com/8166962/168857827-ba5ec6ba-dac1-4a49-b920-2dd145e3681a.png)

If still issues, maybe have a look [here](https://community.spotify.com/t5/Spotify-for-Developers/INVALID-CLIENT-Invalid-redirect-URI/td-p/5228936), particularly at the points about `/callback` or extra `%` chars

**Comment by radujica** [comment] 2023-02-09 21:40
Closing due to no new reply. Welcome to re-open if needed :)

**Closed as not planned by radujica** 2023-02-09 21:40 UTC
